-- Add declaration and body below to existing EB_CORE_SLAB_NEW package.
PROCEDURE GET_EIN_FROM_HRMS(PI_USERCD IN VARCHAR2,OP_EIN OUT VARCHAR2,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2);
PROCEDURE GET_EIN_FROM_HRMS(PI_USERCD IN VARCHAR2,OP_EIN OUT VARCHAR2,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2) AS
BEGIN
 SELECT EIN INTO OP_EIN FROM (SELECT EIN FROM HRMS_VIEW WHERE LOWER(TRIM(EMAIL)) LIKE LOWER(TRIM(PI_USERCD))||'%' ORDER BY EIN) WHERE ROWNUM=1;
 P_STATUS:='SUCCESS';P_MESSAGE:='Employee found in HRMS';
EXCEPTION WHEN NO_DATA_FOUND THEN OP_EIN:=NULL;P_STATUS:='FAIL';P_MESSAGE:='Employee not found in HRMS';
 WHEN OTHERS THEN OP_EIN:=NULL;P_STATUS:='ERROR';P_MESSAGE:=SQLERRM;
END GET_EIN_FROM_HRMS;
/
