CREATE OR REPLACE PACKAGE EB_ADMIN_SLAB_NEW AS
 PROCEDURE GET_USER_BY_EIN(P_SEARCH_VALUE IN VARCHAR2,P_CURSOR OUT SYS_REFCURSOR,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2);
 PROCEDURE GET_ACTIVE_SOLS(P_CURSOR OUT SYS_REFCURSOR,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2);
 PROCEDURE GET_USER_MASTER_LIST(P_CURSOR OUT SYS_REFCURSOR,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2);
 PROCEDURE MAINTAIN_USER_MASTER(P_ACTION IN VARCHAR2,P_EIN_NO IN VARCHAR2,P_USER_CODE IN VARCHAR2,P_SOL_ID IN VARCHAR2,P_USER_STATUS IN VARCHAR2,P_RIGHTS IN VARCHAR2,P_ACTION_BY IN VARCHAR2,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2);
END EB_ADMIN_SLAB_NEW;
/
CREATE OR REPLACE PACKAGE BODY EB_ADMIN_SLAB_NEW AS
 PROCEDURE GET_USER_BY_EIN(P_SEARCH_VALUE IN VARCHAR2,P_CURSOR OUT SYS_REFCURSOR,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2) AS V_COUNT NUMBER;V_EIN VARCHAR2(50);V_S VARCHAR2(20);V_M VARCHAR2(4000);
 BEGIN
  SELECT COUNT(*) INTO V_COUNT FROM IET_USER_MASTER WHERE UPPER(TRIM(EIN_NO))=UPPER(TRIM(P_SEARCH_VALUE)) OR UPPER(TRIM(USER_CODE))=UPPER(TRIM(P_SEARCH_VALUE));
  IF V_COUNT>0 THEN OPEN P_CURSOR FOR SELECT USER_CODE,EIN_NO,SOL_ID,ROLE,STATUS,RIGHTS,ISBULK_UPLOAD,CREATED_BY,CREATION_TIME,MODIFIED_BY,MODIFIED_ON,APPR_RJCT_ON,APPR_RJCT_BY FROM IET_USER_MASTER WHERE UPPER(TRIM(EIN_NO))=UPPER(TRIM(P_SEARCH_VALUE)) OR UPPER(TRIM(USER_CODE))=UPPER(TRIM(P_SEARCH_VALUE)) FETCH FIRST 1 ROW ONLY;
  ELSE EB_CORE_SLAB_NEW.GET_EIN_FROM_HRMS(P_SEARCH_VALUE,V_EIN,V_S,V_M);
   IF V_S='SUCCESS' THEN OPEN P_CURSOR FOR SELECT TRIM(P_SEARCH_VALUE) USER_CODE,V_EIN EIN_NO,CAST(NULL AS VARCHAR2(20)) SOL_ID,CAST(NULL AS VARCHAR2(30)) ROLE,'A' STATUS,CAST(NULL AS VARCHAR2(10)) RIGHTS,CAST(NULL AS VARCHAR2(10)) ISBULK_UPLOAD,CAST(NULL AS VARCHAR2(100)) CREATED_BY,CAST(NULL AS TIMESTAMP) CREATION_TIME,CAST(NULL AS VARCHAR2(100)) MODIFIED_BY,CAST(NULL AS TIMESTAMP) MODIFIED_ON,CAST(NULL AS TIMESTAMP) APPR_RJCT_ON,CAST(NULL AS VARCHAR2(100)) APPR_RJCT_BY FROM DUAL;
   ELSE OPEN P_CURSOR FOR SELECT USER_CODE,EIN_NO,SOL_ID,ROLE,STATUS,RIGHTS,ISBULK_UPLOAD,CREATED_BY,CREATION_TIME,MODIFIED_BY,MODIFIED_ON,APPR_RJCT_ON,APPR_RJCT_BY FROM IET_USER_MASTER WHERE 1=2; END IF;
  END IF;P_STATUS:='SUCCESS';P_MESSAGE:='Lookup completed';
 EXCEPTION WHEN OTHERS THEN P_STATUS:='ERROR';P_MESSAGE:=SQLERRM;END;
 PROCEDURE GET_ACTIVE_SOLS(P_CURSOR OUT SYS_REFCURSOR,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2) AS BEGIN OPEN P_CURSOR FOR SELECT TRIM(SOL_ID) SOL_ID,TRIM(SOL_DESC) SOL_DESC FROM ALL_SOL WHERE UPPER(TRIM(DEL_FLG))='N' ORDER BY SOL_ID;P_STATUS:='SUCCESS';P_MESSAGE:='SOLs fetched';EXCEPTION WHEN OTHERS THEN P_STATUS:='ERROR';P_MESSAGE:=SQLERRM;END;
 PROCEDURE GET_USER_MASTER_LIST(P_CURSOR OUT SYS_REFCURSOR,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2) AS BEGIN OPEN P_CURSOR FOR SELECT USER_CODE,EIN_NO,SOL_ID,ROLE,STATUS,RIGHTS,ISBULK_UPLOAD,CREATED_BY,CREATION_TIME,MODIFIED_BY,MODIFIED_ON,APPR_RJCT_ON,APPR_RJCT_BY FROM IET_USER_MASTER ORDER BY CREATION_TIME DESC;P_STATUS:='SUCCESS';P_MESSAGE:='Users fetched';EXCEPTION WHEN OTHERS THEN P_STATUS:='ERROR';P_MESSAGE:=SQLERRM;END;
 PROCEDURE MAINTAIN_USER_MASTER(P_ACTION IN VARCHAR2,P_EIN_NO IN VARCHAR2,P_USER_CODE IN VARCHAR2,P_SOL_ID IN VARCHAR2,P_USER_STATUS IN VARCHAR2,P_RIGHTS IN VARCHAR2,P_ACTION_BY IN VARCHAR2,P_STATUS OUT VARCHAR2,P_MESSAGE OUT VARCHAR2) AS V_A VARCHAR2(10):=UPPER(TRIM(P_ACTION));V_C NUMBER;
 BEGIN
  IF P_USER_STATUS NOT IN('A','D') THEN RAISE_APPLICATION_ERROR(-20001,'Invalid status');END IF;SELECT COUNT(*) INTO V_C FROM ALL_SOL WHERE TRIM(SOL_ID)=TRIM(P_SOL_ID) AND UPPER(TRIM(DEL_FLG))='N';IF V_C=0 THEN RAISE_APPLICATION_ERROR(-20002,'Invalid SOL');END IF;
  IF V_A='SAVE' THEN INSERT INTO IET_USER_MASTER(USER_CODE,EIN_NO,SOL_ID,STATUS,RIGHTS,CREATED_BY,CREATION_TIME) VALUES(TRIM(P_USER_CODE),TRIM(P_EIN_NO),TRIM(P_SOL_ID),P_USER_STATUS,CASE WHEN P_RIGHTS='ADM' THEN 'ADM' END,P_ACTION_BY,SYSTIMESTAMP);
  ELSIF V_A='UPDATE' THEN UPDATE IET_USER_MASTER SET USER_CODE=TRIM(P_USER_CODE),SOL_ID=TRIM(P_SOL_ID),STATUS=P_USER_STATUS,RIGHTS=CASE WHEN P_RIGHTS='ADM' THEN 'ADM' END,MODIFIED_BY=P_ACTION_BY,MODIFIED_ON=SYSTIMESTAMP WHERE UPPER(TRIM(EIN_NO))=UPPER(TRIM(P_EIN_NO));
  ELSIF V_A='DELETE' THEN DELETE IET_USER_MASTER WHERE UPPER(TRIM(EIN_NO))=UPPER(TRIM(P_EIN_NO));
  ELSIF V_A='REJECT' THEN UPDATE IET_USER_MASTER SET STATUS='D',APPR_RJCT_BY=P_ACTION_BY,APPR_RJCT_ON=SYSTIMESTAMP WHERE UPPER(TRIM(EIN_NO))=UPPER(TRIM(P_EIN_NO));ELSE RAISE_APPLICATION_ERROR(-20003,'Invalid action');END IF;
  P_STATUS:='SUCCESS';P_MESSAGE:=INITCAP(LOWER(V_A))||' completed successfully';EXCEPTION WHEN OTHERS THEN P_STATUS:='ERROR';P_MESSAGE:=SQLERRM;END;
END EB_ADMIN_SLAB_NEW;
/
