spring.application.name=IDBI-eTreasury
server.port=8081
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Local embedded LDAP directory. Replace this configuration/provider for enterprise LDAP.
app.ldap.port=8389
app.ldap.base-dn=dc=idbi,dc=bank

logging.level.in.co.idbibank.etreasury=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n
logging.file.path=${APP_LOG_PATH:logs}
logging.file.name=${logging.file.path}/idbi-etreasury.log
logging.logback.rollingpolicy.file-name-pattern=${logging.file.path}/archive/idbi-etreasury-%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
server.servlet.session.timeout=15m

# Oracle database connection pool
app.datasource.driver-class-name=oracle.jdbc.OracleDriver
app.datasource.jdbc-url=jdbc:oracle:thin:@10.172.26.175:1522:IBNKET
app.datasource.username=ENC(T4Ya9El5dOM5ibG1Y81WhNIgbX66tBckh2RQlpf1aCo544m9P+/vWMVz)
app.datasource.password=ENC(LWKumNsMpDsh3R/8yBaVbyL0j9cuTxGuosq/Z1pZCvF6QUpGcxnVvppp)
app.datasource.encryption-key=be80bfe60bfdf7882040a336300d0664fcf3342982e0996c
app.datasource.pool-name=IDBI-eTreasury-Oracle-Pool
app.datasource.maximum-pool-size=10
app.datasource.minimum-idle=0
app.datasource.connection-timeout=30000
app.datasource.idle-timeout=600000
app.datasource.max-lifetime=1800000
app.datasource.validation-timeout=5000
