<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="icon" href="/favicon.ico" sizes="any"><title>Dashboard | IDBI e-Treasury</title><link href="/assets/vendor/bootstrap/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="/assets/css/treasury-confluence.css"><link rel="stylesheet" href="/assets/css/components/header.css"><link rel="stylesheet" href="/assets/css/components/sidebar.css"><link rel="stylesheet" href="/assets/css/components/footer.css"></head>
<body data-page="home"><div class="app-shell">
  <%@ include file="partials/header.jsp" %>
  <%@ include file="partials/sidebar.jsp" %>
  <main class="main-content"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><div class="page-kicker mb-1">SATURDAY, 18 JULY 2026</div><h1 class="page-title mb-1">Treasury overview</h1><p class="text-secondary small mb-0">Good afternoon, <c:out value="${sessionScope.treasuryUser.userCode}" />. Here is today’s operating position.</p></div><a class="btn btn-idbi" href="/deals/new"><i data-lucide="plus" width="17" class="me-1"></i>New forex deal</a></div>
  <div class="row g-3 mb-3"><div class="col-sm-6 col-xl-3"><div class="panel metric-card"><div class="d-flex justify-content-between"><span class="metric-label">TODAY'S DEALS</span><span class="metric-icon"><i data-lucide="handshake" width="19"></i></span></div><div class="metric-value">128</div><small class="text-success fw-semibold">+12 from yesterday</small></div></div><div class="col-sm-6 col-xl-3"><div class="panel metric-card"><div class="d-flex justify-content-between"><span class="metric-label">DEAL VALUE</span><span class="metric-icon"><i data-lucide="indian-rupee" width="19"></i></span></div><div class="metric-value">₹ 842.6 Cr</div><small class="text-secondary">Across all currencies</small></div></div><div class="col-sm-6 col-xl-3"><div class="panel metric-card"><div class="d-flex justify-content-between"><span class="metric-label">PENDING APPROVAL</span><span class="metric-icon"><i data-lucide="clock-3" width="19"></i></span></div><div class="metric-value">07</div><small class="text-warning-emphasis fw-semibold">Requires attention</small></div></div><div class="col-sm-6 col-xl-3"><div class="panel metric-card"><div class="d-flex justify-content-between"><span class="metric-label">OPEN POSITIONS</span><span class="metric-icon"><i data-lucide="activity" width="19"></i></span></div><div class="metric-value">24</div><small class="text-success fw-semibold">Within limits</small></div></div></div>
  <div class="row g-3"><div class="col-xl-8"><section class="panel h-100"><div class="panel-header d-flex justify-content-between align-items-center"><div><h2 class="panel-title">Recent forex deals</h2><small class="text-secondary">Latest activity across dealing desks</small></div><a class="btn btn-sm btn-light" href="#">View all</a></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th class="ps-3">Deal ID</th><th>Customer</th><th>Pair</th><th>Type</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody><tr><td class="ps-3 fw-bold">FX-260718-0842</td><td>Apex Exports Ltd.</td><td><span class="currency-chip"><span class="currency-flag">US</span>USD/INR</span></td><td>Purchase</td><td class="fw-semibold">$ 425,000</td><td><span class="badge badge-soft-success">Completed</span></td><td><i data-lucide="chevron-right" width="16"></i></td></tr><tr><td class="ps-3 fw-bold">FX-260718-0841</td><td>Nova Engineering</td><td><span class="currency-chip"><span class="currency-flag">EU</span>EUR/INR</span></td><td>Sale</td><td class="fw-semibold">€ 180,000</td><td><span class="badge badge-soft-warning">Pending</span></td><td><i data-lucide="chevron-right" width="16"></i></td></tr><tr><td class="ps-3 fw-bold">FX-260718-0840</td><td>Western Textiles</td><td><span class="currency-chip"><span class="currency-flag">GB</span>GBP/INR</span></td><td>Purchase</td><td class="fw-semibold">£ 96,500</td><td><span class="badge badge-soft-success">Completed</span></td><td><i data-lucide="chevron-right" width="16"></i></td></tr><tr><td class="ps-3 fw-bold">FX-260718-0839</td><td>Orion Pharma</td><td><span class="currency-chip"><span class="currency-flag">US</span>USD/INR</span></td><td>Sale</td><td class="fw-semibold">$ 310,000</td><td><span class="badge badge-soft-danger">On hold</span></td><td><i data-lucide="chevron-right" width="16"></i></td></tr></tbody></table></div></section></div>
  <div class="col-xl-4"><section class="panel h-100"><div class="panel-header"><h2 class="panel-title">Live card rates</h2><small class="text-secondary"><span class="status-dot"></span>Updated 15:48:22 IST</small></div><div class="p-3"><div class="row small fw-bold text-secondary pb-2 border-bottom"><div class="col-4">PAIR</div><div class="col-4 text-end">BUY</div><div class="col-4 text-end">SELL</div></div><div class="row align-items-center py-3 border-bottom"><div class="col-4 fw-bold">USD/INR</div><div class="col-4 text-end">83.4425</div><div class="col-4 text-end fw-bold text-teal">83.4625</div></div><div class="row align-items-center py-3 border-bottom"><div class="col-4 fw-bold">EUR/INR</div><div class="col-4 text-end">90.8540</div><div class="col-4 text-end fw-bold text-teal">90.8940</div></div><div class="row align-items-center py-3"><div class="col-4 fw-bold">GBP/INR</div><div class="col-4 text-end">107.8820</div><div class="col-4 text-end fw-bold text-teal">107.9420</div></div></div></section></div></div>
  <%@ include file="partials/footer.jsp" %></main>
</div><script src="/assets/vendor/lucide/lucide.min.js"></script><script src="/assets/vendor/bootstrap/bootstrap.bundle.min.js"></script><script src="/assets/js/app.js"></script></body></html>
